### ISSUE TITLE
Spring Data Commons 2.0.0 is not compatible

### ISSUE THREAD

**Issue by marceloverdijk** [Cosium/spring-data-jpa-entity-graph#10]
In Spring Data Commons 2.0.0 (currently only milestones being released) `QueryDslPredicateExecutor` seems to be renamed to `QuerydslPredicateExecutor`.

Spring Boot 2.0 uses Spring Data 2.0 so currently there is no way to upgrade from Spring Boot 1.5.x to 2.0.

I don't know why they renamed it but it causes some incompatibilities unfortunately.

**Comment by marceloverdijk** [comment]
But it is related to DATACMNS-867 - Consistent non-capitalization of Querydsl.

Maybe good to do use the same naming for the `spring-data-jpa-entity-graph` project.
That way you probably could also easily support both Spring data < `2.0` and >= `2.0`.

**Comment by mp911de** [comment]
Spring Data 2.0 comes with a series of breaking changes (`CrudRepository` method renaming, restructuring of internal APIs). 2.0 isn't compatible with the 1.x line and requires some effort to upgrade.

**Comment by reda-alaoui** [comment]
Hello,

Thanks for reporting this.
Indeed we have to start upgrading master branch to spring data 2.0.

As usual, PRs are welcomed until I find time to upgrade ;)

**Comment by marceloverdijk** [comment]
👍
