### ISSUE TITLE
How to customize repository base class

### ISSUE THREAD

**Issue by akihyro** [Cosium/spring-data-jpa-entity-graph#11]
This library is what I was looking for. Thanks!
However, I have a question.

How can I customize the repository base class?
I want to use the function of [Spring official document "Adding custom behavior to all repositories"].

[Spring official document "Adding custom behavior to all repositories"]: https://docs.spring.io/spring-data/jpa/docs/1.11.6.RELEASE/reference/html/#repositories.custom-behaviour-for-all-repositories

```java
@NoRepositoryBean
public interface MyRepository<T, ID extends Serializable>
    extends EntityGraphJpaRepository<T, ID> {
    // ...
}
```

```java
@Configuration
@EnableJpaRepositories(
    repositoryBaseClass = MyRepositoryImpl.class,  // <-- customized base class!
    repositoryFactoryBeanClass = EntityGraphJpaRepositoryFactoryBean.class
)
public class DataRepositoryConfiguration {
    //...
}
```

So, I'm thinking to inherit `EntityGraphSimpleJpaRepository` as follows.
But `EntityGraphSimpleJpaRepository` is not public...

```java
public class MyRepositoryImpl<T, ID extends Serializable>
    extends EntityGraphSimpleJpaRepository<T, ID>
    implements MyRepository<T, ID> {
    // ...
}
```

Could you please support this?

Thanks.

**Comment by reda-alaoui** [comment]
Hello @akihyro ,
To allow customization, I just turned the following classes into public classes:
- EntityGraphJpaRepositoryFactory
- EntityGraphQuerydslRepository
- EntityGraphSimpleJpaRepository

Release 1.11.03 containing the fix has been performed.
You will be able to use it in the next hour :)

**Comment by akihyro** [comment]
Thanks for the quick fix! 👍
