### ISSUE TITLE
Spring Data 2.0 uses Optional<T> findOne

### ISSUE THREAD

**Issue by marceloverdijk** [Cosium/spring-data-jpa-entity-graph#13]
The `EntityGraphQuerydslPredicateExecutor` currently uses the following signature:

```
T findOne(Predicate predicate, EntityGraph entityGraph);
```

In Spring Data 2.0 the {{QuerydslPredicateExecutor}} is changed to:

```
Optional<T> findOne(Predicate var1);
```

I think this library should upgrade to the `Optional<T>` as well for `findOne`.

**Comment by marceloverdijk** [comment]
Note `EntityGraphJpaSpecificationExecutor` already does this but `EntityGraphQuerydslPredicateExecutor` not yet.

**Comment by reda-alaoui** [comment]
Yep !
