### ISSUE TITLE
Request documentation help

### ISSUE THREAD

**Issue by dnslin** [Cosium/spring-data-jpa-entity-graph#171]
Could you provide documentation on how to use NamedEntityGraph or DynamicEntityGraph?

Compared to building with the @NamedEntityGraph annotation on the entity class, I would like to know how to dynamically construct using NamedEntityGraph or DynamicEntityGraph to solve the N+1 problem. I look forward to your reply. Thank you.

**Comment by reda-alaoui** [comment]
Just read the README.md?
