### ISSUE TITLE
Equals and hashCode on AbstractEntityGraph?

### ISSUE THREAD

**Issue by thyming** [Cosium/spring-data-jpa-entity-graph#21]
This is maybe a question and maybe and issue - I ran into a problem where I had introduced this project as a dependency (thanks!) but mock calls were failing to match because I (incorrectly) assumed that `EntityGraphs.named("x").equals(EntityGraphs.named("x"))` is true. Is there a reason that equals and hashCode are not implemented? Would you accept a PR adding this to AbstractEntityGraph?

**Comment by reda-alaoui** [comment]
Hi @thyming ,

There are no equals/hashCode on AbstractEntityGraph because I didn't have a use for them.
I would gladly accept a PR adding them :+1:
