### ISSUE TITLE
EntityGraphJpaRepositoryFactoryBean and @DataJpaTest

### ISSUE THREAD

**Issue by tuure** [Cosium/spring-data-jpa-entity-graph#25]
I try to test my service with repository that use EntityGraphJpaRepository and always get 
Failed to create query for method public abstract java.util.List xxx.findByProjectPublicId(java.lang.String,com.cosium.spring.data.jpa.entity.graph.domain.EntityGraph)! At least 2 parameter(s) provided but only 1 parameter(s) present in query.
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:82)

**Comment by reda-alaoui** [comment]
As stated in https://github.com/Cosium/spring-data-jpa-entity-graph/blob/master/doc/MAIN.md#quick-start, you must set `repositoryFactoryBeanClass`.
