### ISSUE TITLE
Support MongoDB so applications can use either Spring Data JPA and Spring Data Mongo

### ISSUE THREAD

**Issue by ddcruver** [Cosium/spring-data-jpa-entity-graph#27]
I know the concept of EntityGraphs do not map to MongoDB databases but would like to see an addition to this library so it could be used in applications that want to support running with either a JPA or Mongo Database.

Something like com.cosium.spring.data.jpa.entity.graph.repository.support.EntityGraphMongoDBRepositoryFactoryBean which will just create repositories that will ignore the Named Entity parameter on invocations.

Possibly include this library in a separate module so it does not force people to include Spring Data Mongo dependencies.

**Comment by reda-alaoui** [comment]
Sorry, but this project is only dedicated to Spring Data JPA, nothing else.
