### ISSUE TITLE
Java 12 Support

### ISSUE THREAD

**Issue by ben-schroeder** [Cosium/spring-data-jpa-entity-graph#28]
Hi there, 

I just tried to use spring-data-jpa-entity-graph 2.1.0 with openjdk-12.0.1 and it throws a NoSuchFieldException:

`Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2417)
	at com.cosium.spring.data.jpa.entity.graph.repository.support.EntityGraphJpaRepositoryFactory.addEntityGraphToSpecialTypes(EntityGraphJpaRepositoryFactory.java:58)
	... 52 common frames omitted`

Thanks in advance for looking into this.

**Comment by reda-alaoui** [comment]
This will be fixed by #23 
Meanwhile, like in JDK 11, I think you can permit illegal access with `--illegal-access=permit`.

**Comment by RomainWilbert** [comment]
This does not work with JDK 13 either
 --illegal-access=permit changes nothing

**Comment by reda-alaoui** [comment]
@RomainWilbert , take a look at https://github.com/Cosium/spring-data-jpa-entity-graph/issues/23#issuecomment-573799772
