### ISSUE TITLE
findAll with pageable is not working well with entitygraphs 

### ISSUE THREAD

**Issue by chaoyangnz** [Cosium/spring-data-jpa-entity-graph#29]
Hi, I have two entities, A has a @OneToMany relation to B. then i set entitygraph and expect to retrieve nested B in one SQL.

When i use findAll with pageable, it doesn’t do pagination, no limit is generated . instead it will load the whole table.

**Comment by reda-alaoui** [comment]
Hi @chaoyangnz ,

This is caused by [Hibernate](https://vladmihalcea.com/fix-hibernate-hhh000104-entity-fetch-pagination-warning-message/)

**Comment by reda-alaoui** [comment]
I strongly encourage you to enable [this](https://vladmihalcea.com/hibernate-query-fail-on-pagination-over-collection-fetch/)
