### ISSUE TITLE
Use Specfications without extra join 

### ISSUE THREAD

**Issue by mosiobahmani** [Cosium/spring-data-jpa-entity-graph#32]
hi 
Thanks for your library that makes me very happy.
i have a question :
how to use Specfication without extra join (Join<x,y>) with  our entityGraph?
in our namedEntityGraph actually we are joining Entities together and now i want to set where clause on the one of those subGraph to fetch with that.
is ther any way?
(sorry for my bad English)

**Comment by reda-alaoui** [comment]
Hi,

I didn't understand your question.
Can you provide an example?

**Comment by mosiobahmani** [comment]
When we use entityGraph and subgrpah actualy like writing left outer
join.ok?
Example:

Select person.name, person.lastname, city.name, city.code
From tbl_person person
 Left outer join tbl_city city On person.city_id = city.id

Its the query that hibernate create for this:
@NamedEntityGraph("person_city" , attributes:"city"

Now i want use specification on my entityGraph, but i need to set where
cluse with city (or other attributes)
Like:

Select person.name, person.lastname, city.name, city.code
From tbl_person person
 Left outer join tbl_city city On person.city_id = city.id
Where city.name = "NewYork"

How can i do it ?
( i dont want to use another extra Join<person,City> )

Tnx

**Comment by reda-alaoui** [comment]
IMO, you can't do it differently.
Moreover, this library is not meant to solve such issue.

I think your question should be addressed to the JPA specification maintainers.
