### ISSUE TITLE
Repository bean not found 

### ISSUE THREAD

**Issue by Rahul1d** [Cosium/spring-data-jpa-entity-graph#39]
Hi,

 I am using spring jpa 2.2.6.RELEASE and spring-data-jpa-entity-graph 2.2.8.
I have added  @EnableJpaRepositories(repositoryFactoryBeanClass = 
 EntityGraphJpaRepositoryFactoryBean.class) to config class.

Repository bean is Extending EntityGraphJpaRepository<T, Integer>,EntityGraphQuerydslPredicateExecutor<T>.

I have followed all steps as mentiioned in the docs.

JPA Config.
        `
            @Configuration
            @EnableJpaAuditing(auditorAwareRef = "auditorAware") 
            @EnableJpaRepositories(repositoryFactoryBeanClass = 
                EntityGraphJpaRepositoryFactoryBean.class)
            //@EnableJpaRepositories
            public class JpaConfig {
            
            @Bean
            public AuditorAware<String> auditorAware() {
                return new AuditorImpl();
            }
            
            @Bean
            public JPAQueryFactory jpaQueryFactory(EntityManager entityManager)
            {
                return new JPAQueryFactory(entityManager);
            }
            } `

Repository:.

            `
            public interface GeneralRepository<T> extends EntityGraphJpaRepository<T, Integer>,EntityGraphQuerydslPredicateExecutor<T> {

            }
            `

**Comment by ylcinyakup** [comment]
@Configuration
@EnableJpaRepositories(repositoryFactoryBeanClass = EntityGraphJpaRepositoryFactoryBean.class, basePackages = {"com.dummy.app.repository"})
public class RepositoryConfig {
}

**Comment by reda-alaoui** [comment]
Hi @ylcinyakup ,

There must be something wrong with your Spring configuration.
We used this version in production without issue.

If you can't provide your full application git repository, I can't help you.

**Comment by ylcinyakup** [comment]
i just write @Rahul1d questions answer :D he should set basePackages value

**Comment by reda-alaoui** [comment]
Oh ok @ylcinyakup :)

**Comment by Rahul1d** [comment]
The basePackage  was missing . Thanks @ylcinyakup .

**Comment by benodeveloper** [comment]
> @configuration @EnableJpaRepositories(repositoryFactoryBeanClass = EntityGraphJpaRepositoryFactoryBean.class, basePackages = {"com.dummy.app.repository"}) public class RepositoryConfig { }
Life saver, this works well for me
