### ISSUE TITLE
Cannot find @NamedSubgraph Capability

### ISSUE THREAD

**Issue by VladyslavLevchuk** [Cosium/spring-data-jpa-entity-graph#42]
There is Department entity that has field LocationEntity as @ManyToOne. LocationEntity entity has several fields streetAddress, postalCode, city etc... If I specify EntityGraphUtils.fromAttributePaths(new String[] {"department.location", "department.location.streetAddress"}) I can see that Hibernate fetches all fields from location table even though I specified only streetAddress field. I've been wondering if there is any capability such as @NamedSubgraph to able to specify only the needed fields to be fetched from child entity?

**Comment by reda-alaoui** [comment]
It seems you didn’t understand entitygraph purpose. This is not a place for questions about the JPA specification or Hibernate. 
Your question is suited for stackoverflow.

**Comment by VladyslavLevchuk** [comment]
@reda-alaoui But why? There isn't any example with subgraphs using this lib in your docs. I can see only this simple one EntityGraphUtils.fromAttributePaths("brand", "maker"). But what about subgraph capability? This is strictly directed to this lib and I thought that it is kind of a bug to fetch all table fields even though I specify only the needed one  for fromAttributePaths(...). I think this would be helpfull for others too...

**Comment by reda-alaoui** [comment]
https://github.com/Cosium/spring-data-jpa-entity-graph/issues/24

**Comment by ylcinyakup** [comment]
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections.interfaces
Vlad is projections not enough for you ?
