### ISSUE TITLE
Multiple/Default EntityGraphs

### ISSUE THREAD

**Issue by JamesPeters98** [Cosium/spring-data-jpa-entity-graph#51]
Hey! Is it currently possible to set the default entity graph and then have any DynamicEntityGraph's just add attributes on top of the default.

I have a scenario where I'd like certain fields in an Entity to always be Fetched and then be able to choose what other fields using the EntityGraph supplied!

**Comment by reda-alaoui** [comment]
Hey,

If you use Hibernate, since https://hibernate.atlassian.net/browse/HHH-8776, the concept of "default" EntityGraph defined by this extension is not needed anymore.
You can just rely on your Entity annotations fetch type and apply an EntityGraph of type LOAD `javax.persistence.loadgraph`.

Here is an example:

```java
@Entity
class A {
  @OneToOne(fetchType = EAGER)
  private B b;

  @OneToOne(fetchType = LAZY)
  private C c;
}
```

```java
// This will load b + c
aRepository.findById(1, new DynamicEntityGraph(LOAD, Collections.singletonList("c")));
```

**Comment by reda-alaoui** [comment]
From https://docs.oracle.com/javaee/7/tutorial/persistence-entitygraphs001.htm :

> To specify a load graph, set the javax.persistence.loadgraph property when you execute an EntityManager.find or query operation. A load graph consists of the fields explicitly specified in the EntityGraph instance plus any fields in the default entity graph.

**Comment by JamesPeters98** [comment]
I had tried that but it doesn't work with Spring Boot and Spring Data which appears to just ignore FetchType Completely, that's why I'm using Entity Graphs in the first place
