### ISSUE TITLE
Extend documentation for @EnableJpaRepositories

### ISSUE THREAD

**Issue by v-ladynev** [Cosium/spring-data-jpa-entity-graph#52]
Provide an additional example with `basePackages` in case if the configuration in a separate package.

```
@Configuration
@EnableJpaRepositories(repositoryFactoryBeanClass = EntityGraphJpaRepositoryFactoryBean.class, basePackages = "net.xxx.service.base")
public class DataRepositoryConfiguration {

}
```

**Comment by reda-alaoui** [comment]
Using this extension requires the user to know how to use/configure Spring Data JPA.
Usage of `basePackages` is (or should be) described in Spring Data JPA documentation.
