### ISSUE TITLE
Would it be possible to have a EntityGraphRepository?

### ISSUE THREAD

**Issue by marceloverdijk** [Cosium/spring-data-jpa-entity-graph#6]
In my project I'm extending the ordinary `org.springframework.data.repository.Repository` as I don't want to expose all the default crud stuff.

Would that be possible with this library?

**Comment by reda-alaoui** [comment]
Hello @marceloverdijk ,

I just made the test:

```
public interface MakerRepository extends Repository<Maker, Long> {

	List<Maker> findByName(String name, EntityGraph entityGraph);

}
```

Yes, a `org.springframework.data.repository.Repository` will work :)

I will update the documentation about that.

**Comment by reda-alaoui** [comment]
Documentation and test added.
I think I answered your question.

If not, feel free to reopen ;)

**Comment by marceloverdijk** [comment]
Cool, will try it today!
