### ISSUE TITLE
Throw when using @Lock and default graph

### ISSUE THREAD

**Issue by slkmikhail** [Cosium/spring-data-jpa-entity-graph#60]
**What steps will reproduce the problem?**
1. Create custom jpa repository method and put @Lock
```java
@Lock(LockModeType.PESSIMISTIC_WRITE)
Optional<Person> findAndLockById(UUID id)
```
2. Add field to **Person**
```java
@OneToMany(mappedBy = "person", fetch = FetchType.LAZY)
private List<Address> addresses
```
3. Add default graph to **Person** (Person.default) with 
```java
....
@NamedAttributeNode(address)
```
4. Do query by **findAndLockById**

**What is the expected output?**
Find and lock without entity graph
**What happens instead?**
```
org.postgresql.util.PSQLException: ERROR: FOR UPDATE cannot be applied to the nullable side of an outer join
```
**Environment:**
 - Spring Data JPA version (not the Spring Boot one): **2.5.2**
 - ORM with version: **5.6.1**
 - spring-data-jpa-entity-graph version: **2.5.0**

Is there some way not to use default entity graph for some jpa methods?

**Comment by reda-alaoui** [comment]
The `default entity graph` concept introduced a long time ago by this library is not needed anymore (see https://github.com/Cosium/spring-data-jpa-entity-graph/issues/44#issuecomment-642469698 for the rationale).
So I would just tell you to stop using it.

**Comment by slkmikhail** [comment]
The `default entity graph` is a good staff to avoid a suggestion which EG should be used for standard jpa methods every time when should be fetched additional data (less code)
More flexibale feature would be to use the `default entity graph` as is, but have capability to:
1. extend the `default entity graph` dynamicly by passing additional EG to some method
`PersonEntityGraph.____(APPEND) .....`
2. disable the `default entity graph` for some methods by an annotation or another way (in my case)

**Comment by reda-alaoui** [comment]
> The default entity graph is a good staff to avoid a suggestion which EG should be used for standard jpa methods every time when should be fetched additional data (less code)

You can now achieve the same behaviour by only relying on your entity attributes annotations. Here is an example:
```java
public class Product {
  @ManyToOne(fetch = FetchType.LAZY)
  private Brand brand;
  @ManyToOne(fetch = FetchType.EAGER)
  private Manufacturer manufacturer;
}
```

In this example, the default entity graph is `(manufacturer)`.

**Comment by slkmikhail** [comment]
As I know, unfortunately, the `FetchType.EAGER` strategy is also prone to N+1 query issues. That is not a good solution for fetch a lot of data.

**Comment by reda-alaoui** [comment]
You can use `default` interface methods to pass "default" entity like this:

```
default Optional<Person> findByName(UUID id) {
  return findByName(id, NamedEntityGraph.loading("foo.default"));
}

Optional<Person> findByName(UUID id, EntityGraph entityGraph);
```
