### ISSUE TITLE
spring-data-jpa-entity-graph-generator with gradle throws ClassCastException

### ISSUE THREAD

**Issue by bnagy1996** [Cosium/spring-data-jpa-entity-graph#61]
I get the following error while building with gradle: 

class com.sun.tools.javac.code.Type$ArrayType cannot be cast to class javax.lang.model.type.DeclaredType (com.sun.tools.javac.code.Type$ArrayType is in module jdk.compiler of loader 'app'; javax.lang.model.type.DeclaredType is in module java.compiler of loader 'platform')

An extract from build.gradle with lombok and querydsl: 

implementation 'org.hibernate:hibernate-java8:5.6.1.Final'
annotationProcessor 'org.hibernate:hibernate-jpamodelgen:5.4.0.Final'
implementation 'com.cosium.spring.data:spring-data-jpa-entity-graph:2.5.0'
annotationProcessor 'com.cosium.spring.data:spring-data-jpa-entity-graph-generator:2.5.0'

Entity_ files are generated, if annotationProcessor 'com.cosium.spring.data:spring-data-jpa-entity-graph-generator:2.5.0' is removed from the build.

**Comment by reda-alaoui** [comment]
The bug report template was not used.
