### ISSUE TITLE
Allow usage of smallest repository interfaces

### ISSUE THREAD

**Issue by marceloverdijk** [Cosium/spring-data-jpa-entity-graph#7]
Spring Data JPA `1.11.x` includes a `QueryByExampleExecutor` (part of Spring Data Commons >=`1.12`).

It would be nice to have a `JpaEntityGraphQueryByExampleExecutor` to support providing the entity graph.

**Comment by reda-alaoui** [comment]
Good idea indeed.

Could you make a PR for this?

**Comment by marceloverdijk** [comment]
Hi @reda-alaoui I'm not requiring this `JpaEntityGraphQueryByExampleExecutor` currently but I think this might be useful to be included in the lib.

**Comment by reda-alaoui** [comment]
Ok no problem

**Comment by reda-alaoui** [comment]
In fact `JpaEntityGraphRepository` is already a `QueryByExampleExecutor`.

![image](https://cloud.githubusercontent.com/assets/2890843/24071503/c3560f3c-0bd3-11e7-8b96-aefb6b62abb6.png)

And all `QueryByExampleExecutor` methods completed with EntityGraphs are available in `JpaEntityGraphRepository`.

Maybe you want a repository interface that would only expose `QueryByExampleExecutor` methods?

More globally, I think that a good enhancement would be to split `JpaEntityGraphRepository` into new entitygraph repositories for:
- CrudRepository
- PagingAndSortingRepository
- QueryByExampleExecutor

This would let people take the smaller needed interface, like you did with `org.springframework.data.repository.Repository`.

**Comment by marceloverdijk** [comment]
Well done!
